### PR TITLE
Shm implementation

### PR DESCRIPTION
**Pull request by KinhTruongUnikie**
The program can be run only with the combination of --help(optional), --shm \<shm name\> and --file \<file name\>(in any order), any other combinations will result exit error.
The main implementation sits in ipc_methods.c.

P.S short option e.g -h -s also work

### CODE REVIEW

**Review by RomainChaumontet — CHANGES_REQUESTED** [review]
I am not sure it will work because the shmSend can doing multiple loops before the shmReceive wake up to lock mutex. You should use semaphore or write a sleep in the loop.

**Comment by KinhTruongUnikie** [comment]
I think that should not be a problem. After the first iteration sent value is set to 1, during the second loop shmSend would end up in condvar wait, and unlock the mutex, then the mutex is available for shmReceive to use again. So in practice, shmSend and shmReceive can only take turn to touch the data because of the while loop condition of shm_ptr->sent

**Comment by RomainChaumontet** [comment]
Oh yes sorry I read the code too quickly. 

I am still not sure that's work because I tried it, but I give you the doubt! ;)

**Review by RomainChaumontet — APPROVED** [review]

**Comment by KinhTruongUnikie** [comment]
No problem, it is not easy to review now because our licenses already expired. If you have anything unclear about my code feel free to discuss with me anytime

**Review by baovu-unikie — APPROVED** [review]

**Pull request merged**
